services:
  postgres:
    container_name: postgres-sql-auth
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: authenticationDB
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: always
networks:
  spring-demo:
    driver: bridge
volumes:
  postgres:
    driver: local